language: node_js
node_js: 
  - 8.11.2


# S: Build Lifecycle
install:
  - npm install
  - git clone git://github.com/shenliyang/hexo-theme-snippet.git themes/snippet
  - rm -f ./themes/snippet/_config.yml
  - mv ./_config.yml.themes ./themes/snippet/_config.yml

script:
  - hexo clean && hexo g
  

after_script:
  - cd ./public
  - echo "blog.shijf.top" >> CNAME
  - git init
  - git config user.name "shijf"
  - git config user.email "shijf_private@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/Shijf/shijf.github.io.git