language: node_js
node_js: 
  - 8.11.2


# S: Build Lifecycle
install:
  - npm install

script:
  - hexo clean && hexo g
  

after_script:
  - ls
  - ls ./public
  - hexo -v
  - npm -v
  - hexo clean && hexo g
  - cd ./public
  - echo "blog.shijf.top" >> CNAME
  - git init
  - git config user.name "shijf"
  - git config user.email "shijf_private@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/Shijf/shijf.github.io.git